services:

  app:
    build: .
    container_name: node-app
    environment:
      - PG_DB=crud-db
      - PG_USER=admin
      - PG_PASSWORD=password
      - PG_HOST=db
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

